jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            app:
                namespace_prefix: "App\\ValueObject"
                path: "%kernel.project_dir%/config/serializer"