jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    metadata:
        auto_detection: true
        directories:
            app:
                namespace_prefix: "App\\DTO"
                path: "%kernel.project_dir%/config/serializer"