nelmio_api_doc:
    documentation:
        info:
            title: Some cool App!
            description: This is an awesome app!
            version: 0.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^(?!/documentation$)