version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
      - ./var/container/log:/var/log/nginx
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
      - ./var/container/log/xdebug.log:/tmp/xdebug.log